[project]
name = "openpi-client"
version = "0.1.0"
requires-python = ">=3.7"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["pytest>=8.3.4"]

[tool.ruff]
line-length = 120
target-version = "py37"
